apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onyxia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mauknl/homelab-cluster.git
    targetRevision: main
    path: onyxia   # <--- IMPORTANT: Point to the folder containing kustomization.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: onyxia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
