apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onyxia
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://inseefrlab.github.io/onyxia
    chart: onyxia
    targetRevision: 10.32.0
    helm:
      values: |
        # --- 1. Onyxia API Configuration ---
        api:
          nodeSelector:
            kubernetes.io/hostname: rpi5-master
          
          # [CRITICAL FIX] DNS Hijack: Map external domain to internal Traefik IP
          hostAliases:
            - ip: "10.43.157.160"
              hostnames:
                - "auth.100.83.110.77.nip.io"
                - "datalab.100.83.110.77.nip.io"

          # Force OIDC Settings via Environment Variables
          extraEnv:
            - name: AUTHENTICATION_MODE
              value: "openidconnect"
            - name: OIDC_ISSUER_URI
              value: "https://auth.100.83.110.77.nip.io/realms/datalab"
            - name: OIDC_CLIENT_ID
              value: "onyxia"
            # Trust Self-Signed Certs (since we are staying internal)
            - name: OIDC_SKIP_TLS_VERIFY 
              value: "true"
            
            # S3 Credentials
            - name: ONYXIA_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: onyxia-s3-creds
                  key: accessKeyId
            - name: ONYXIA_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: onyxia-s3-creds
                  key: secretAccessKey

        web:
          nodeSelector:
            kubernetes.io/hostname: rpi5-master

        # --- 2. General Settings ---
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hosts:
            - host: datalab.100.83.110.77.nip.io
              paths: ["/"]
          tls:
            - secretName: wildcard-tls
              hosts:
                - datalab.100.83.110.77.nip.io

        security:
          oidc:
            enabled: true
            clientId: onyxia
            issuerUri: "https://auth.100.83.110.77.nip.io/realms/datalab"
            ssl:
              trustStore:
                enabled: false

        s3:
          enabled: true
          URL: "http://minio.minio.svc:9000"
          region: "us-east-1"
          accessKeyId: ""
          secretAccessKey: ""

        # --- 3. User Workspace Configuration ---
        regions:
          - id: geekom-cluster
            name: "Geekom Lab (x86)"
            type: kubernetes
            namespacePrefix: "user-"
            nodeSelector:
              kubernetes.io/hostname: geekom-power
            tolerations:
              - key: "workload"
                operator: "Equal"
                value: "heavy"
                effect: "NoSchedule"
            ingress:
              domain: "100.83.110.77.nip.io"
              ingressClassName: traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
            tls:
               enabled: true
               secretName: wildcard-tls
            initScript: |
              kubectl get secret wildcard-tls -n onyxia -o json \
              | jq 'del(.metadata.namespace,.metadata.creationTimestamp,.metadata.resourceVersion,.metadata.uid)' \
              | kubectl apply -f -

  # --- THIS IS THE PART THAT WAS MISSING ---
  destination:
    server: https://kubernetes.default.svc
    namespace: onyxia
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
