apiVersion: v1
kind: Namespace
metadata:
  name: vscode
---
# 1. The Storage (Hard Drive Space)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc-power
  namespace: vscode
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: local-path
---
# 2. The Application (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-power
  namespace: vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server-power
  template:
    metadata:
      labels:
        app: code-server-power
    spec:
      # A. PIN TO GEEKOM (The Power Node)
      nodeSelector:
        kubernetes.io/hostname: "geekom-power"

      # B. THE GAS MASK (Allow running on tainted node)
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "heavy"
        effect: "NoSchedule"

      containers:
      - name: code-server
        image: lscr.io/linuxserver/code-server:latest
        imagePullPolicy: Always

        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - |
                  # Run in background to avoid blocking startup
                  nohup bash -c '
                  echo "🚀 [K8s Hook] Starting installation..." > /config/install.log

                  # 1. Wait for Internet
                  for i in {1..30}; do ping -c 1 8.8.8.8 && break; sleep 1; done

                  # 2. Update & Install Tools
                  apt-get update
                  apt-get install -y wget curl git golang-go r-base python3-pip python3-venv build-essential

                  # 3. Install Julia (x86_64 Version for Geekom)
                  if [ ! -f "/usr/local/bin/julia" ]; then
                    echo "☕ Downloading Julia (x86_64)..." >> /config/install.log
                    # NOTE: Changed from aarch64 to linux-x86_64 for Geekom
                    wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.4-linux-x86_64.tar.gz -O /tmp/julia.tar.gz
                    mkdir -p /opt/julia
                    tar -xzf /tmp/julia.tar.gz -C /opt/julia --strip-components 1
                    ln -sf /opt/julia/bin/julia /usr/local/bin/julia
                    rm /tmp/julia.tar.gz
                  fi

                  echo "✅ [K8s Hook] Installation Complete!" >> /config/install.log
                  ' > /config/k8s-debug.log 2>&1 &

        # C. ENVIRONMENT VARIABLES
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-auth
              key: password
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Amsterdam"

        ports:
        - containerPort: 8443

        # D. MOUNT STORAGE
        volumeMounts:
        - name: code-storage
          mountPath: /config
      volumes:
      - name: code-storage
        persistentVolumeClaim:
          claimName: code-pvc-power
---
# 3. The Internal Network
apiVersion: v1
kind: Service
metadata:
  name: code-server-power
  namespace: vscode
spec:
  ports:
  - port: 80
    targetPort: 8443
  selector:
    app: code-server-power
---
# 4. The Public Address
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-power
  namespace: vscode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - code-power.192.168.1.179.nip.io
    secretName: wildcard-tls

  rules:
  - host: code-power.192.168.1.179.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server-power
            port:
              number: 80
