apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glances
  namespace: kube-system
  labels:
    app: glances
spec:
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      # 1. See the host's Network (IPs, Up/Down speeds)
      hostNetwork: true
      # 2. See the host's Processes (Fixes the "2 Tasks" issue)
      hostPID: true

      tolerations:
      - operator: "Exists"

      containers:
      - name: glances
        image: nicolargo/glances:latest-full
        # "-w" starts web server
        command: ["/usr/local/bin/glances", "-w", "-t", "10"]
        securityContext:
          # 3. Grant hardware access (Fixes Temperature & permissions)
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 50Mi
        ports:
        - containerPort: 61208
          hostPort: 61208
          name: http
        volumeMounts:
        - mountPath: /sys/class/thermal
          name: thermal
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker
          readOnly: true
      volumes:
      - name: thermal
        hostPath:
          path: /sys/class/thermal
      - name: docker
        hostPath:
          path: /var/run/docker.sock
