apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glances
  namespace: kube-system
  labels:
    app: glances
spec:
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      # Host Network allows seeing real Upload/Download speeds
      hostNetwork: true
      containers:
      - name: glances
        image: nicolargo/glances:latest-full
        command: ["/usr/local/bin/glances", "-w"]
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 50Mi
        ports:
        - containerPort: 61208
          hostPort: 61208
          name: http
        # Mounts for Temperature and Docker stats
        volumeMounts:
        - mountPath: /sys/class/thermal
          name: thermal
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker
          readOnly: true
      volumes:
      - name: thermal
        hostPath:
          path: /sys/class/thermal
      - name: docker
        hostPath:
          path: /var/run/docker.sock
